project:
  type: website
  output-dir: docs

website:
  title: "phd things"
  navbar:
    left:
      - href: index.qmd
        text: home
      - text: semester summaries 
        menu:
          - sem-summaries/s1.qmd
          - sem-summaries/s2.qmd
          - sem-summaries/s2-5.qmd
          - sem-summaries/s3.qmd
          - sem-summaries/s4.qmd
      - text: general exams
        menu:
          - general-exams/reading-list.qmd
          - economics-general.qmd
          - econometrics-intro.qmd
          - chinas-growth.qmd
          - micro-theory.qmd
      - text: research
        menu:
          - research-ideas/transit-project-rti.qmd
          - rio-project.qmd
          - world-bank-rct-1.qmd
          - world-bank-rct-2.qmd
      - text: random/other
        menu:
          - text: Old blog
            href: https://aguidetosomething.notion.site/65abc11924624cda98677f2495d70312

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    self-contained: true

editor: source