project:
  type: website
  output-dir: docs

website:
  title: "ashley's phd notes"
  navbar:
    left:
      - href: index.qmd
        text: home
      - text: semester summaries 
        menu:
          - phd-summary-goals-plan.qmd
          - phd-summary-s1.qmd
          - phd-summary-s2.qmd
          - phd-summary-s2-5.qmd
          - phd-summary-s3.qmd
          - phd-summary-s4.qmd
      - text: general exams
        menu:
          - reading-list-by-topic.qmd
          - economics-general.qmd
          - econometrics-intro.qmd
          - chinas-growth.qmd
          - micro-theory.qmd
      - text: research
        menu:
          - rio-project.qmd
          - world-bank-rct-1.qmd
          - world-bank-rct-2.qmd
      - text: random/other
        menu:
          - math-tools.qmd
          - causal-inference.qmd
          - ci-and-hypothesis-testing.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    self-contained: true

editor: visual