---
title: "goals/plan/schedule"
---

# Goals

-   Do **meaningful** research, that I enjoy, that will have an **impact**

-   Learn about topics that are **meaningful** to me

-   Becoming a Professor! (or, a World Bank Economist)

# Schedule

## High-level

::: {style="text-align: center;"}
```{mermaid center}

flowchart TD
    A[Year 1] --> F(Coursework) --> G(First Year Paper)
    B[Year 2] --> H(Coursework) --> I(General Exams)
    C[Year 3] --> J(Thesis Proposal) --> K(Thesis Writing)
    D[Year 4] --> L(Thesis Writing)
    E[Year 5] --> M(Thesis Writing)

```
:::

## Classes

::: panel-tabset
### Year 1

| Subject | Title | Units | Level | Grade |
|-----------|-------------------------------|-----------|-----------|-----------|
| 11.233 | Research Design for Policy Analysis and Planning | 12 | G | A |
| 11.258 | Sustainable Urbanization Research Seminar | 3 | G | P |
| 11.919 | PhD Workshop | 1 | G | P |
| 21H.992 | Economic Classics: The History of Economic Ideas from Ancient Times to Present | 12 | G | A |
| CS50 | Introduction to Computer Science | 12 | N | P |
| 11.234 | Making Sense: Qualitative Methods for Designers and Planners | 12 | G | B+ |
| 11.800 | Doctoral Research Seminar | 9 | G | P |
| 11.801 | Doctoral Research Paper | 9 | G | A |
| 11.919 | PhD Workshop | 1 | G | P |

### Year 2

| Subject | Title                                            | Units | Level | Grade |
|------------|--------------------------|------------|------------|------------|
| 14.003  | Microeconomic Theory and Public Policy           | 12    | G     |       |
| 14.300  | Introduction to Statistical Methods in Economics | 12    | G     | A+    |
| 14.410  | Public Finance and Public Policy                 | 12    | G     | A     |
| 11.919  | PhD Workshop                                     | 1     | G     | P     |
|         |                                                  |       |       |       |
|         |                                                  |       |       |       |
|         |                                                  |       |       |       |
|         |                                                  |       |       |       |
|         |                                                  |       |       |       |

### Year 3

Content for Tab 3.

### Year 4

Content for Tab 4.

### Year 5

Content for Tab 5.
:::
