---
title: "Semester 2"
format: 
  html:
    toc: true
    page-layout: full
---

## Highlights

-   Trip to Brazil
-   Won a \$20,000 grant for my Rio de Janeiro Public Transit research project from the MIT Sloan Latin American Office. Only three projects won from “dozens of submissions”. My project competed against MIT Faculty, so I was very pleased to win.
-   I successfully led the effort to increase the Conference Fund for PhD students from \$600 to \$1,300 per year.
-   I sat on the PhD Committee for both semesters and was part of the PhD Workshop organising team for the Spring semester.
-   I was part of the Graduate Student Union Constitution Committee helping shape the GSU constitution.
-   I also became a Resident Advisor for my graduate dormitory, The Warehouse.
-   TA for Prof. Juan Palacios in the Spring. Both were wonderful experiences where I learned a lot.

## Pictures!

:::::::: columns
::: {.column width="30%"}
pics
:::

::: {.column width="5%"}
:::

::: {.column width="30%"}
pics
:::

::: {.column width="5%"}
:::

::: {.column width="30%"}
pics
:::
::::::::
